export default {
  meta: {
    name: { en: "Yusuke Shono", ja: "庄野祐輔" },
    title: { en: "Editor & Curator", ja: "編集者・キュレーター" },
    location: { en: "Tokyo", ja: "東京" },
    updated: "2026-05-26",
  },

  profile: {
    en: "Yusuke Shono is an editor and curator working across two practices — publishing and exhibitions. With MASSAGE MAGAZINE as his base, he has built a space of discourse and display centered on digital, generative, and computer art. His recent curatorial projects investigate contemporary technologies such as blockchain and AI, and through major exhibitions at NEORT++ (Bakurochō, Tokyo) he is building networks across digital art communities at home and abroad.",
    ja: "編集者・キュレーターとして、出版・展覧会の二つの実践を横断する。雑誌『MASSAGE MAGAZINE』を母体に、デジタル／ジェネラティブ／コンピューターアートを中心とした言説と展示の場を構築。近年はブロックチェーンやAIなど現代のテクノロジーについて探求するキュレーションを展開し、NEORT++（東京・馬喰町）での主要展示を通じて、国内外のデジタルアートのネットワークを構築している。",
  },

  roles: [
    {
      role: { en: "Publisher / Editor-in-Chief", ja: "発行人・編集長" },
      org: { en: "MASSAGE MAGAZINE", ja: "MASSAGE MAGAZINE" },
      since: "2004",
    },
    {
      role: { en: "Editor-in-Chief", ja: "編集長" },
      org: { en: "100 Japanese Motion Graphic Creators (BNN)", ja: "映像作家100人（BNN）" },
      since: "2005",
    },
    {
      role: { en: "Curator (continuing partner)", ja: "継続パートナー・キュレーター" },
      org: { en: "NEORT++, Tokyo", ja: "NEORT++（東京）" },
      since: "2022",
    },
    {
      role: { en: "Committee Member / Curator", ja: "実行委員・キュレーター" },
      org: { en: "Proof of X", ja: "Proof of X" },
      since: "2022",
    },
    {
      role: { en: "Contributor", ja: "寄稿者" },
      org: { en: "Right Click Save", ja: "Right Click Save" },
      since: "2022",
    },
  ],

  entries: [
    {
      id: "2025-12-patterns-of-entanglement",
      year: 2025,
      sort: "2025-12-04",
      date: { en: "Dec 2025", ja: "2025年12月" },
      type: "CURATORIAL",
      title: { en: "Patterns of Entanglement", ja: "もつれのパターン" },
      role: { en: "Co-curation", ja: "共同キュレーション" },
      venue: { en: "NEORT++, Tokyo", ja: "NEORT++（東京）" },
      collaborators: { en: "with Alex Estorick (Right Click Save)", ja: "アレックス・エストリック（Right Click Save）と共同" },
      note: {
        en: "An international exhibition on media ecologies and AI, presented alongside five digital studies released in collaboration with Verse.",
        ja: "メディア・エコロジーとAIをめぐる国際展。Verseと連動した5点のデジタル・スタディも公開。",
      },
      url: "https://two.neort.io/en/exhibitions/patterns_of_entanglement",
      ref_url: "https://www.rightclicksave.com/article/tokyo-sets-stage-for-exhibition-of-media-ecologies-patterns-of-entanglement-neort",
      ref_label: { en: "Review at Right Click Save", ja: "Right Click Saveでの紹介" },
    },
    {
      id: "2025-09-computational-poetry",
      year: 2025,
      sort: "2025-09-19",
      date: { en: "Sep–Oct 2025", ja: "2025年9〜10月" },
      type: "CURATORIAL",
      title: { en: "Computational Poetry", ja: "計算する詩" },
      role: { en: "Co-curation", ja: "共同キュレーション" },
      venue: { en: "NEORT++, Tokyo", ja: "NEORT++（東京）" },
      collaborators: { en: "with Zeroichi Arakawa (IAMAS)", ja: "荒川零一（IAMAS）と共同" },
      note: {
        en: "Re-reading the 1950s concrete poetry concept of \"verbivocovisual\" as a poetics of code. Presented in conjunction with Verse Works.",
        ja: "1950年代のコンクリート・ポエトリーが掲げた『verbivocovisual』を、コードによる詩学として読み直す。Verse Works連動。",
      },
      url: "https://verse.works/exhibitions/computational-poetry",
    },
    {
      id: "2025-04-moment-talk",
      year: 2025,
      sort: "2025-04-06",
      date: { en: "Apr 2025", ja: "2025年4月" },
      type: "CRITICAL",
      title: { en: "MOMENT 2025: Talk with hasaqui", ja: "NEORT++ 3rd Anniversary『MOMENT』トーク" },
      role: { en: "Speaker", ja: "登壇" },
      venue: { en: "NEORT++, Tokyo", ja: "NEORT++（東京）" },
      collaborators: { en: "with hasaqui", ja: "hasaquiと対談" },
      url: "https://www.youtube.com/watch?v=Rygne0XNZ1Q",
    },
    {
      id: "2025-massage-publisher",
      year: 2025,
      sort: "2025-01-01",
      date: { en: "Ongoing", ja: "継続中" },
      type: "EDITORIAL",
      title: { en: "MASSAGE MAGAZINE", ja: "MASSAGE MAGAZINE" },
      role: { en: "Publisher / Editor-in-Chief", ja: "発行人・編集長" },
      note: {
        en: "Founded in 2004; continuing operation.",
        ja: "2004年創刊。継続運営中。",
      },
    },
    {
      id: "2024-10-foot-foot",
      year: 2024,
      sort: "2024-10-01",
      date: { en: "Oct 2024", ja: "2024年10月" },
      type: "CURATORIAL",
      title: { en: "Foot Foot", ja: "Foot Foot" },
      role: { en: "Curation", ja: "キュレーション" },
      venue: { en: "NEORT++, Tokyo (DESIGNART TOKYO 2024)", ja: "NEORT++（東京、DESIGNART TOKYO 2024提携）" },
      note: {
        en: "Focused on the work of Kazuhiro Aihara.",
        ja: "相原一弘の作品にフォーカス。",
      },
    },
    {
      id: "2024-10-patterns-of-flow",
      year: 2024,
      sort: "2024-09-15",
      date: { en: "Sep–Oct 2024", ja: "2024年9〜10月" },
      type: "CURATORIAL",
      title: { en: "Patterns of Flow", ja: "流れのパターン" },
      role: { en: "Co-curation", ja: "共同キュレーション" },
      venue: { en: "NEORT++, Tokyo", ja: "NEORT++（東京）" },
      collaborators: { en: "with Alex Estorick (Right Click Save)", ja: "アレックス・エストリック（Right Click Save）と共同" },
      note: {
        en: "Revisiting early Japanese computer art through the work of Hiroshi Kawano. Related DOMMUNE talk in October 2024.",
        ja: "川野洋を起点に、日本黎明期のコンピュータアートを再考。DOMMUNE関連トーク（2024年10月）を併催。",
      },
      url: "https://x.com/DOMMUNE/status/1840852632992432387",
      ref_label: { en: "DOMMUNE talk", ja: "DOMMUNEトーク" },
    },
    {
      id: "2024-machine-made-aura",
      year: 2024,
      sort: "2024-06-01",
      date: { en: "2024", ja: "2024年" },
      type: "CURATORIAL",
      title: { en: "Machine-Made Aura", ja: "Machine-Made Aura" },
      role: { en: "Curation", ja: "キュレーション" },
      venue: { en: "K Art Gallery", ja: "K Art Gallery" },
    },
    {
      id: "2024-05-web-as-a-medium",
      year: 2024,
      sort: "2024-05-10",
      date: { en: "May 2024", ja: "2024年5月" },
      type: "CURATORIAL",
      title: { en: "Web as a Medium", ja: "Web as a Medium ／ メディウムとしてのウェブ" },
      role: { en: "Co-curation (MASSAGE MAGAZINE × NEORT++)", ja: "共同キュレーション（MASSAGE MAGAZINE × NEORT++）" },
      venue: { en: "NEORT++, Tokyo", ja: "NEORT++（東京）" },
      note: {
        en: "Presented with the Tezos NFT platform objkt.one, including an NFT drop on May 16. Artists: 0xhaiku, exonemo, Canek Zapata, Damjanski, Jan Robert Leegte, Joan Heemskerk, Kitasenju Design, Leander Herzog, Violet Forest, Yehwan Song.",
        ja: "Tezos NFTプラットフォーム objkt.one と連動、5月16日にNFTドロップを実施。出展作家：0xhaiku、exonemo、Canek Zapata、Damjanski、Jan Robert Leegte、Joan Heemskerk、Kitasenju Design、Leander Herzog、Violet Forest、Yehwan Song。",
      },
      url: "https://two.neort.io/ja/exhibitions/web_as_a_medium",
    },
    {
      id: "2024-01-proof-of-x-pfp",
      year: 2024,
      sort: "2024-01-12",
      date: { en: "Jan 2024", ja: "2024年1月" },
      type: "CURATORIAL",
      title: { en: "Proof of X — Decoding PFP Culture", ja: "Proof of X — Decoding PFP Culture" },
      role: { en: "Committee / Curation", ja: "実行委員・キュレーション" },
      venue: { en: "Shibuya PARCO Gallery X, Tokyo", ja: "SHIBUYA PARCO GALLERY X（東京）" },
      note: {
        en: "Featuring Akihiro Kato, CryptoCitizens (Bright Moments), CryptoPunks, int art, Kai Yoshizawa + Baku Hashimoto + MASSAGE MAGAZINE, KUMALEON, Milady Maker, Mitchell F. Chan, Nahiko, NIINOMI, PIV, Toshi (A to Z).",
        ja: "出展作家：加藤明洋、CryptoCitizens（Bright Moments）、CryptoPunks、int art、Kai Yoshizawa + Baku Hashimoto + MASSAGE MAGAZINE、KUMALEON、Milady Maker、Mitchell F. Chan、Nahiko、NIINOMI、PIV、Toshi（A to Z）。",
      },
      url: "https://prtimes.jp/main/html/rd/p/000000012.000041243.html",
    },
    {
      id: "2023-on-curation-rcs",
      year: 2023,
      sort: "2023-09-01",
      date: { en: "2023", ja: "2023年" },
      type: "CRITICAL",
      title: { en: "On Curation — Blockchain as a New Medium", ja: "On Curation — ブロックチェーンを新たなメディウムとして" },
      role: { en: "Author", ja: "執筆" },
      venue: { en: "Right Click Save (curatorial essay series, vol. 1)", ja: "Right Click Save（キュレトリアル・エッセイ・シリーズ第1回）" },
      note: {
        en: "Right Click Save described Shono as \"the architect of Proof of X\" sharing his vision for blockchain as a medium.",
        ja: "Right Click Save編集部の紹介：『the architect of Proof of X shares his vision for blockchain as a medium』。",
      },
      url: "https://www.rightclicksave.com/article/on-curation-yusuke-shono-proof-of-x-digital-art",
    },
    {
      id: "2023-jagda-democratization",
      year: 2023,
      sort: "2023-08-01",
      date: { en: "2023", ja: "2023年" },
      type: "CRITICAL",
      title: { en: "The Democratization and Fluidity of Expression", ja: "表現の民主化と流動性" },
      role: { en: "Author", ja: "執筆" },
      venue: { en: "JAGDA — The Graphic Design Review", ja: "JAGDA『The Graphic Design Review』" },
      note: {
        en: "From Beeple's Christie's sale ($69,346,250), the essay traces how digital tools, social media, and blockchain chain together to mark the endpoint of the \"democratization of expression.\"",
        ja: "BeepleによるChristie'sでの落札（$69,346,250）を起点に、デジタルツール・SNS・ブロックチェーンが連鎖して生んだ『表現の民主化』の最終地点を論じる。",
      },
      url: "https://gdr.jagda.or.jp/articles/63/",
    },
    {
      id: "2023-06-proof-of-x",
      year: 2023,
      sort: "2023-06-17",
      date: { en: "Jun 2023", ja: "2023年6月" },
      type: "CURATORIAL",
      title: { en: "Proof of X — Blockchain As A New Medium For Art", ja: "Proof of X — Blockchain As A New Medium For Art" },
      role: { en: "Curator commentary / Committee", ja: "キュレーター・コメンタリー／実行委員" },
      venue: { en: "THE FACE DAIKANYAMA, Tokyo", ja: "THE FACE DAIKANYAMA（東京）" },
      note: {
        en: "Featuring exonemo (Proof of Non-Existence, 2023), 0xDEAFBEEF (Caves, 2022), 0xhaiku, PIV (Default Punks, 2022), and others.",
        ja: "出展：exonemo『Proof of Non-Existence』（2023）、0xDEAFBEEF『Caves』（2022）、0xhaiku、PIV『Default Punks』（2022）ほか。",
      },
      url: "https://www.jiji.com/jc/article?k=000000008.000047269&g=prt",
    },
    {
      id: "2023-06-dommune-proof-of-x",
      year: 2023,
      sort: "2023-06-14",
      date: { en: "Jun 2023", ja: "2023年6月" },
      type: "CRITICAL",
      title: { en: "Proof of X @ DOMMUNE", ja: "Proof of X @ DOMMUNE" },
      role: { en: "Speaker", ja: "登壇" },
      venue: { en: "SUPER DOMMUNE", ja: "SUPER DOMMUNE" },
      note: {
        en: "Lineup: Akihiro Kato, ALTERNATIVE MACHINE, Ara, EXCALIBUR, Gin, hasaqui, NIINOMI, Toshi, Yusuke Shono, and others.",
        ja: "登壇：Akihiro Kato、ALTERNATIVE MACHINE、Ara、EXCALIBUR、Gin、hasaqui、NIINOMI、Toshi、庄野祐輔ほか。",
      },
      url: "https://www.dommune.com/streamings/2023/061401/",
    },
    {
      id: "2023-eizo100-newcomer",
      year: 2023,
      sort: "2023-04-19",
      date: { en: "Apr 2023", ja: "2023年4月" },
      type: "EDITORIAL",
      title: { en: "100 Japanese Motion Graphic Creators + NEWCOMER", ja: "映像作家100人 ＋NEWCOMER" },
      role: { en: "Editor-in-Chief / Designer", ja: "編集長・デザイナー" },
      venue: { en: "BNN", ja: "BNN" },
      note: {
        en: "The first print edition in six years. 100 main creators plus 100 NEWCOMERs. ISBN 978-4-8025-1269-5.",
        ja: "6年ぶりの書籍版。本編100人＋NEWCOMER 100人。ISBN 978-4-8025-1269-5。",
      },
      url: "https://bnn.co.jp/products/9784802512695",
    },
    {
      id: "2022-12-right-click-live",
      year: 2022,
      sort: "2022-12-11",
      date: { en: "Dec 2022", ja: "2022年12月" },
      type: "CRITICAL",
      title: { en: "Right Click Live × KUMALEON", ja: "Right Click Live ／ Right Click Save × KUMALEON" },
      role: { en: "Panelist + Reporter", ja: "パネリスト・寄稿" },
      venue: { en: "Tokyo", ja: "東京" },
      note: {
        en: "Panel \"NFTs and the New Creator Economy\" with Yukiko Shikata, Keitaro Shii, hasaqui, and Yusuke Shono. Resulting Right Click Save report: \"Right Click Live and Japan's New NFT Scene.\"",
        ja: "パネル『NFTs and the New Creator Economy』（四方幸子、椎啓太平、庄野祐輔、hasaqui）。Right Click Saveに寄稿レポート『Right Click Live and Japan's New NFT Scene』。",
      },
      url: "https://www.rightclicksave.com/article/right-click-live-and-japan-new-nft-scene",
    },
    {
      id: "2022-new-creator-economy",
      year: 2022,
      sort: "2022-09-01",
      date: { en: "2022", ja: "2022年" },
      type: "EDITORIAL",
      title: { en: "THE NEW CREATOR ECONOMY", ja: "THE NEW CREATOR ECONOMY ── NFTが生み出す新しいアートの形" },
      role: { en: "Lead Editor + Contributor (\"CryptoArt Pre-History\")", ja: "リードエディター・寄稿（『クリプトアート前史』）" },
      venue: { en: "BNN", ja: "BNN" },
      note: {
        en: "Co-editors: hasaqui, Tsuyoshi Hirose, Noriko Taguchi, Natsumi Fujita. Contributors: Yukiko Shikata, Shunsuke Takao, Ayumu Nagamatsu, Kosuke Nagai, consome, MaskJiro, nobumei, and others.",
        ja: "共同編集：hasaqui、廣瀬剛、田口典子、藤田夏海。寄稿：四方幸子、高尾俊介、永松歩、永井幸輔、consome、MaskJiro、nobumeiほか。",
      },
    },
    {
      id: "2022-04-proof-of-x-1",
      year: 2022,
      sort: "2022-04-01",
      date: { en: "Apr 2022", ja: "2022年4月" },
      type: "CURATORIAL",
      title: { en: "Proof of X — NFT as New Media Art", ja: "Proof of X — NFT as New Media Art" },
      role: { en: "Committee / Curation", ja: "実行委員・キュレーション" },
      venue: { en: "NEORT++, Tokyo", ja: "NEORT++（東京）" },
      note: {
        en: "First edition of the Proof of X series.",
        ja: "「Proof of X」シリーズ第1回。",
      },
    },
    {
      id: "2019-phenomenon-rgb",
      year: 2019,
      sort: "2019-01-01",
      date: { en: "2019", ja: "2019年" },
      type: "CURATORIAL",
      title: { en: "PHENOMENON: RGB", ja: "PHENOMENON: RGB" },
      role: { en: "Curation", ja: "キュレーション" },
      venue: { en: "Laforet Museum Harajuku, Tokyo", ja: "Laforet Museum Harajuku（東京）" },
      note: {
        en: "Treating the RGB display environment as a \"second nature,\" the show brought together creators across art, design, and fashion.",
        ja: "赤・緑・青の三色で構築されるディスプレイ環境を『第二の自然』と見なし、アート・デザイン・ファッションを横断するクリエイターを結集。",
      },
      url: "https://www.laforet.ne.jp/museum_event/RGB/",
    },
    {
      id: "2015-massage-10",
      year: 2015,
      sort: "2015-06-06",
      date: { en: "Jun 2015", ja: "2015年6月" },
      type: "EDITORIAL",
      title: { en: "MASSAGE 10 (print issue)", ja: "MASSAGE 10" },
      role: { en: "Editor", ja: "編集" },
      venue: { en: "MASSAGE", ja: "MASSAGE" },
      note: {
        en: "B5 variant, 120 pages.",
        ja: "B5変形、120頁。",
      },
    },
    {
      id: "2014-massage-9",
      year: 2014,
      sort: "2014-01-10",
      date: { en: "Jan 2014", ja: "2014年1月" },
      type: "EDITORIAL",
      title: { en: "MASSAGE 9 — Internet Culture", ja: "MASSAGE 9 — 特集 INTERNET CULTURE" },
      role: { en: "Editor (with Kentaro Takaoka)", ja: "編集（高岡謙太郎と共同）" },
      venue: { en: "MASSAGE", ja: "MASSAGE" },
      note: {
        en: "256 pages, with included CD. Release event INTERNET CULTURE SHOP @ TOKYO CULTUART by BEAMS.",
        ja: "256頁、CD付。リリースイベント『INTERNET CULTURE SHOP』@ TOKYO CULTUART by BEAMS。",
      },
    },
    {
      id: "2005-eizo100-launch",
      year: 2005,
      sort: "2005-01-01",
      date: { en: "2005", ja: "2005年" },
      type: "EDITORIAL",
      title: { en: "100 Japanese Motion Graphic Creators — Launch", ja: "映像作家100人 — 創刊" },
      role: { en: "Editor-in-Chief", ja: "編集長" },
      venue: { en: "BNN", ja: "BNN" },
      note: {
        en: "Editor-in-chief continuing since.",
        ja: "以降、編集長として継続。",
      },
    },
    {
      id: "2004-massage-launch",
      year: 2004,
      sort: "2004-01-01",
      date: { en: "2004", ja: "2004年" },
      type: "EDITORIAL",
      title: { en: "MASSAGE — Launch", ja: "MASSAGE 創刊" },
      role: { en: "Founder / Editor-in-Chief", ja: "創刊・編集長" },
      note: {
        en: "Founded as a print independent magazine focused on \"events\" in culture.",
        ja: "文化における〈出来事〉を扱う紙のインディペンデント・マガジンとして創刊。",
      },
    },
    {
      id: "1990s-indie-mags",
      year: 1995,
      sort: "1995-01-01",
      date: { en: "1990s", ja: "1990年代" },
      type: "EDITORIAL",
      title: { en: "Independent magazines", ja: "インディペンデント・マガジンの編集" },
      role: { en: "Editor", ja: "編集" },
      note: {
        en: "Editing independent magazines with collaborators.",
        ja: "仲間と共にインディペンデント・マガジンを発行。",
      },
    },
  ],

  writings: [
    {
      year: 2025,
      title: { en: "The Artists at the Intersection (Patterns of Entanglement feature)", ja: "The Artists at the Intersection（Patterns of Entanglement特集）" },
      venue: "Right Click Save",
      kind: { en: "Co-author (with Alex Estorick)", ja: "共著（アレックス・エストリック）" },
    },
    {
      year: 2025,
      title: { en: "Tokyo Sets Stage for Exhibition of Media Ecologies", ja: "Tokyo Sets Stage for Exhibition of Media Ecologies" },
      venue: "Right Click Save",
      kind: { en: "Co-author", ja: "共著" },
    },
    {
      year: 2025,
      title: { en: "Computational Poetry (review)", ja: "Computational Poetry（レビュー）" },
      venue: "MASSAGE MAGAZINE (EN)",
      kind: { en: "Editor / Author", ja: "編集・執筆" },
    },
    {
      year: 2023,
      title: { en: "The Democratization and Fluidity of Expression", ja: "表現の民主化と流動性" },
      venue: "JAGDA — The Graphic Design Review",
      kind: { en: "Author", ja: "執筆" },
    },
    {
      year: 2023,
      title: { en: "On Curation — Blockchain as a New Medium", ja: "On Curation — Blockchain as a New Medium" },
      venue: "Right Click Save",
      kind: { en: "Author", ja: "執筆" },
    },
    {
      year: 2022,
      title: { en: "Right Click Live and Japan's New NFT Scene", ja: "Right Click Live and Japan's New NFT Scene" },
      venue: "Right Click Save",
      kind: { en: "Author", ja: "執筆" },
    },
    {
      year: 2022,
      title: { en: "CryptoArt Pre-History", ja: "クリプトアート前史" },
      venue: "THE NEW CREATOR ECONOMY (BNN)",
      kind: { en: "Author", ja: "執筆" },
    },
  ],

  contact: {
    email_user: "info",
    email_domain: "yusukeshono.com",
  },
};
